// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.0
// source: proto/brutus.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Описание системы
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      int32                  `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_brutus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Описание устройства
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SystemId      int32                  `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Room          string                 `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_brutus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceInfo) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DeviceInfo) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

// Описание параметра
type ParameterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterId   int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PanelVisible  int32                  `protobuf:"varint,5,opt,name=panel_visible,json=panelVisible,proto3" json:"panel_visible,omitempty"` // 1 - видим, 0 - скрыт
	IsControl     bool                   `protobuf:"varint,6,opt,name=is_control,json=isControl,proto3" json:"is_control,omitempty"`          // true - управляемый параметр, false - только мониторинг
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterInfo) Reset() {
	*x = ParameterInfo{}
	mi := &file_proto_brutus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterInfo) ProtoMessage() {}

func (x *ParameterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterInfo.ProtoReflect.Descriptor instead.
func (*ParameterInfo) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterInfo) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *ParameterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ParameterInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterInfo) GetPanelVisible() int32 {
	if x != nil {
		return x.PanelVisible
	}
	return 0
}

func (x *ParameterInfo) GetIsControl() bool {
	if x != nil {
		return x.IsControl
	}
	return false
}

// Текущее значение или запись истории параметра
type ParameterUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterId   int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterUpdate) Reset() {
	*x = ParameterUpdate{}
	mi := &file_proto_brutus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterUpdate) ProtoMessage() {}

func (x *ParameterUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterUpdate.ProtoReflect.Descriptor instead.
func (*ParameterUpdate) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{3}
}

func (x *ParameterUpdate) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *ParameterUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ParameterUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Аутентификация
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_brutus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_brutus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Подписка на обновления
// Клиент указывает, какие параметры хочет слушать
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterIds  []int32                `protobuf:"varint,1,rep,packed,name=parameter_ids,json=parameterIds,proto3" json:"parameter_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_brutus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetParameterIds() []int32 {
	if x != nil {
		return x.ParameterIds
	}
	return nil
}

type ListSystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Systems       []*SystemInfo          `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemsResponse) Reset() {
	*x = ListSystemsResponse{}
	mi := &file_proto_brutus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemsResponse) ProtoMessage() {}

func (x *ListSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemsResponse.ProtoReflect.Descriptor instead.
func (*ListSystemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{7}
}

func (x *ListSystemsResponse) GetSystems() []*SystemInfo {
	if x != nil {
		return x.Systems
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      int32                  `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_brutus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{8}
}

func (x *ListDevicesRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_brutus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{9}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VisibleOnly   bool                   `protobuf:"varint,2,opt,name=visible_only,json=visibleOnly,proto3" json:"visible_only,omitempty"` // вернуть только panel_visible=1, если true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParametersRequest) Reset() {
	*x = ListParametersRequest{}
	mi := &file_proto_brutus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParametersRequest) ProtoMessage() {}

func (x *ListParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParametersRequest.ProtoReflect.Descriptor instead.
func (*ListParametersRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{10}
}

func (x *ListParametersRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ListParametersRequest) GetVisibleOnly() bool {
	if x != nil {
		return x.VisibleOnly
	}
	return false
}

type ListParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*ParameterInfo       `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParametersResponse) Reset() {
	*x = ListParametersResponse{}
	mi := &file_proto_brutus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParametersResponse) ProtoMessage() {}

func (x *ListParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParametersResponse.ProtoReflect.Descriptor instead.
func (*ListParametersResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{11}
}

func (x *ListParametersResponse) GetParameters() []*ParameterInfo {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// История значений
type HistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParameterId    int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_brutus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryRequest) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *HistoryRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *HistoryRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ParameterUpdate     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_brutus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryResponse) GetValues() []*ParameterUpdate {
	if x != nil {
		return x.Values
	}
	return nil
}

// Команды параметрам
type SetParameterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterId   int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParameterRequest) Reset() {
	*x = SetParameterRequest{}
	mi := &file_proto_brutus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParameterRequest) ProtoMessage() {}

func (x *SetParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParameterRequest.ProtoReflect.Descriptor instead.
func (*SetParameterRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{14}
}

func (x *SetParameterRequest) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *SetParameterRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetParameterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Updated       *ParameterUpdate       `protobuf:"bytes,2,opt,name=updated,proto3" json:"updated,omitempty"` // опционально вернуть новое значение
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParameterResponse) Reset() {
	*x = SetParameterResponse{}
	mi := &file_proto_brutus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParameterResponse) ProtoMessage() {}

func (x *SetParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParameterResponse.ProtoReflect.Descriptor instead.
func (*SetParameterResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{15}
}

func (x *SetParameterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetParameterResponse) GetUpdated() *ParameterUpdate {
	if x != nil {
		return x.Updated
	}
	return nil
}

var File_proto_brutus_proto protoreflect.FileDescriptor

const file_proto_brutus_proto_rawDesc = "" +
	"\n" +
	"\x12proto/brutus.proto\x12\x06brutus\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\n" +
	"SystemInfo\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\x05R\bsystemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\x05R\bsystemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04room\x18\x05 \x01(\tR\x04room\"\xb2\x01\n" +
	"\rParameterInfo\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rpanel_visible\x18\x05 \x01(\x05R\fpanelVisible\x12\x1d\n" +
	"\n" +
	"is_control\x18\x06 \x01(\bR\tisControl\"h\n" +
	"\x0fParameterUpdate\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"7\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rparameter_ids\x18\x01 \x03(\x05R\fparameterIds\"C\n" +
	"\x13ListSystemsResponse\x12,\n" +
	"\asystems\x18\x01 \x03(\v2\x12.brutus.SystemInfoR\asystems\"1\n" +
	"\x12ListDevicesRequest\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\x05R\bsystemId\"C\n" +
	"\x13ListDevicesResponse\x12,\n" +
	"\adevices\x18\x01 \x03(\v2\x12.brutus.DeviceInfoR\adevices\"W\n" +
	"\x15ListParametersRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12!\n" +
	"\fvisible_only\x18\x02 \x01(\bR\vvisibleOnly\"O\n" +
	"\x16ListParametersResponse\x125\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x15.brutus.ParameterInfoR\n" +
	"parameters\"\x81\x01\n" +
	"\x0eHistoryRequest\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x03 \x01(\x03R\fendTimestamp\"B\n" +
	"\x0fHistoryResponse\x12/\n" +
	"\x06values\x18\x01 \x03(\v2\x17.brutus.ParameterUpdateR\x06values\"N\n" +
	"\x13SetParameterRequest\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"c\n" +
	"\x14SetParameterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\aupdated\x18\x02 \x01(\v2\x17.brutus.ParameterUpdateR\aupdated2\x80\x04\n" +
	"\fMQTTReceiver\x124\n" +
	"\x05Login\x12\x14.brutus.LoginRequest\x1a\x15.brutus.LoginResponse\x12J\n" +
	"\x13SubscribeParameters\x12\x18.brutus.SubscribeRequest\x1a\x17.brutus.ParameterUpdate0\x01\x12B\n" +
	"\vListSystems\x12\x16.google.protobuf.Empty\x1a\x1b.brutus.ListSystemsResponse\x12F\n" +
	"\vListDevices\x12\x1a.brutus.ListDevicesRequest\x1a\x1b.brutus.ListDevicesResponse\x12O\n" +
	"\x0eListParameters\x12\x1d.brutus.ListParametersRequest\x1a\x1e.brutus.ListParametersResponse\x12F\n" +
	"\x13GetParameterHistory\x12\x16.brutus.HistoryRequest\x1a\x17.brutus.HistoryResponse\x12I\n" +
	"\fSetParameter\x12\x1b.brutus.SetParameterRequest\x1a\x1c.brutus.SetParameterResponseB\x14Z\x12brutus/proto;protob\x06proto3"

var (
	file_proto_brutus_proto_rawDescOnce sync.Once
	file_proto_brutus_proto_rawDescData []byte
)

func file_proto_brutus_proto_rawDescGZIP() []byte {
	file_proto_brutus_proto_rawDescOnce.Do(func() {
		file_proto_brutus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_brutus_proto_rawDesc), len(file_proto_brutus_proto_rawDesc)))
	})
	return file_proto_brutus_proto_rawDescData
}

var file_proto_brutus_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_brutus_proto_goTypes = []any{
	(*SystemInfo)(nil),             // 0: brutus.SystemInfo
	(*DeviceInfo)(nil),             // 1: brutus.DeviceInfo
	(*ParameterInfo)(nil),          // 2: brutus.ParameterInfo
	(*ParameterUpdate)(nil),        // 3: brutus.ParameterUpdate
	(*LoginRequest)(nil),           // 4: brutus.LoginRequest
	(*LoginResponse)(nil),          // 5: brutus.LoginResponse
	(*SubscribeRequest)(nil),       // 6: brutus.SubscribeRequest
	(*ListSystemsResponse)(nil),    // 7: brutus.ListSystemsResponse
	(*ListDevicesRequest)(nil),     // 8: brutus.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 9: brutus.ListDevicesResponse
	(*ListParametersRequest)(nil),  // 10: brutus.ListParametersRequest
	(*ListParametersResponse)(nil), // 11: brutus.ListParametersResponse
	(*HistoryRequest)(nil),         // 12: brutus.HistoryRequest
	(*HistoryResponse)(nil),        // 13: brutus.HistoryResponse
	(*SetParameterRequest)(nil),    // 14: brutus.SetParameterRequest
	(*SetParameterResponse)(nil),   // 15: brutus.SetParameterResponse
	(*emptypb.Empty)(nil),          // 16: google.protobuf.Empty
}
var file_proto_brutus_proto_depIdxs = []int32{
	0,  // 0: brutus.ListSystemsResponse.systems:type_name -> brutus.SystemInfo
	1,  // 1: brutus.ListDevicesResponse.devices:type_name -> brutus.DeviceInfo
	2,  // 2: brutus.ListParametersResponse.parameters:type_name -> brutus.ParameterInfo
	3,  // 3: brutus.HistoryResponse.values:type_name -> brutus.ParameterUpdate
	3,  // 4: brutus.SetParameterResponse.updated:type_name -> brutus.ParameterUpdate
	4,  // 5: brutus.MQTTReceiver.Login:input_type -> brutus.LoginRequest
	6,  // 6: brutus.MQTTReceiver.SubscribeParameters:input_type -> brutus.SubscribeRequest
	16, // 7: brutus.MQTTReceiver.ListSystems:input_type -> google.protobuf.Empty
	8,  // 8: brutus.MQTTReceiver.ListDevices:input_type -> brutus.ListDevicesRequest
	10, // 9: brutus.MQTTReceiver.ListParameters:input_type -> brutus.ListParametersRequest
	12, // 10: brutus.MQTTReceiver.GetParameterHistory:input_type -> brutus.HistoryRequest
	14, // 11: brutus.MQTTReceiver.SetParameter:input_type -> brutus.SetParameterRequest
	5,  // 12: brutus.MQTTReceiver.Login:output_type -> brutus.LoginResponse
	3,  // 13: brutus.MQTTReceiver.SubscribeParameters:output_type -> brutus.ParameterUpdate
	7,  // 14: brutus.MQTTReceiver.ListSystems:output_type -> brutus.ListSystemsResponse
	9,  // 15: brutus.MQTTReceiver.ListDevices:output_type -> brutus.ListDevicesResponse
	11, // 16: brutus.MQTTReceiver.ListParameters:output_type -> brutus.ListParametersResponse
	13, // 17: brutus.MQTTReceiver.GetParameterHistory:output_type -> brutus.HistoryResponse
	15, // 18: brutus.MQTTReceiver.SetParameter:output_type -> brutus.SetParameterResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_brutus_proto_init() }
func file_proto_brutus_proto_init() {
	if File_proto_brutus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_brutus_proto_rawDesc), len(file_proto_brutus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brutus_proto_goTypes,
		DependencyIndexes: file_proto_brutus_proto_depIdxs,
		MessageInfos:      file_proto_brutus_proto_msgTypes,
	}.Build()
	File_proto_brutus_proto = out.File
	file_proto_brutus_proto_goTypes = nil
	file_proto_brutus_proto_depIdxs = nil
}
