// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/brutus.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MQTTReceiver_Login_FullMethodName               = "/brutus.MQTTReceiver/Login"
	MQTTReceiver_SubscribeParameters_FullMethodName = "/brutus.MQTTReceiver/SubscribeParameters"
	MQTTReceiver_ListSystems_FullMethodName         = "/brutus.MQTTReceiver/ListSystems"
	MQTTReceiver_ListDevices_FullMethodName         = "/brutus.MQTTReceiver/ListDevices"
	MQTTReceiver_ListParameters_FullMethodName      = "/brutus.MQTTReceiver/ListParameters"
	MQTTReceiver_GetParameterHistory_FullMethodName = "/brutus.MQTTReceiver/GetParameterHistory"
	MQTTReceiver_SetParameter_FullMethodName        = "/brutus.MQTTReceiver/SetParameter"
)

// MQTTReceiverClient is the client API for MQTTReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------------------
// Сервис
// -------------------------
type MQTTReceiverClient interface {
	// Авторизация
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Подписка на поток изменений
	SubscribeParameters(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParameterUpdate], error)
	// Получение информации об объекте
	ListSystems(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSystemsResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ListParameters(ctx context.Context, in *ListParametersRequest, opts ...grpc.CallOption) (*ListParametersResponse, error)
	// История значений
	GetParameterHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	// Отправка команды параметру
	SetParameter(ctx context.Context, in *SetParameterRequest, opts ...grpc.CallOption) (*SetParameterResponse, error)
}

type mQTTReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewMQTTReceiverClient(cc grpc.ClientConnInterface) MQTTReceiverClient {
	return &mQTTReceiverClient{cc}
}

func (c *mQTTReceiverClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTReceiverClient) SubscribeParameters(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParameterUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MQTTReceiver_ServiceDesc.Streams[0], MQTTReceiver_SubscribeParameters_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ParameterUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MQTTReceiver_SubscribeParametersClient = grpc.ServerStreamingClient[ParameterUpdate]

func (c *mQTTReceiverClient) ListSystems(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSystemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSystemsResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_ListSystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTReceiverClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTReceiverClient) ListParameters(ctx context.Context, in *ListParametersRequest, opts ...grpc.CallOption) (*ListParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParametersResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_ListParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTReceiverClient) GetParameterHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_GetParameterHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTReceiverClient) SetParameter(ctx context.Context, in *SetParameterRequest, opts ...grpc.CallOption) (*SetParameterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetParameterResponse)
	err := c.cc.Invoke(ctx, MQTTReceiver_SetParameter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MQTTReceiverServer is the server API for MQTTReceiver service.
// All implementations must embed UnimplementedMQTTReceiverServer
// for forward compatibility.
//
// -------------------------
// Сервис
// -------------------------
type MQTTReceiverServer interface {
	// Авторизация
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Подписка на поток изменений
	SubscribeParameters(*SubscribeRequest, grpc.ServerStreamingServer[ParameterUpdate]) error
	// Получение информации об объекте
	ListSystems(context.Context, *emptypb.Empty) (*ListSystemsResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListParameters(context.Context, *ListParametersRequest) (*ListParametersResponse, error)
	// История значений
	GetParameterHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	// Отправка команды параметру
	SetParameter(context.Context, *SetParameterRequest) (*SetParameterResponse, error)
	mustEmbedUnimplementedMQTTReceiverServer()
}

// UnimplementedMQTTReceiverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMQTTReceiverServer struct{}

func (UnimplementedMQTTReceiverServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMQTTReceiverServer) SubscribeParameters(*SubscribeRequest, grpc.ServerStreamingServer[ParameterUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeParameters not implemented")
}
func (UnimplementedMQTTReceiverServer) ListSystems(context.Context, *emptypb.Empty) (*ListSystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSystems not implemented")
}
func (UnimplementedMQTTReceiverServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedMQTTReceiverServer) ListParameters(context.Context, *ListParametersRequest) (*ListParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParameters not implemented")
}
func (UnimplementedMQTTReceiverServer) GetParameterHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParameterHistory not implemented")
}
func (UnimplementedMQTTReceiverServer) SetParameter(context.Context, *SetParameterRequest) (*SetParameterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetParameter not implemented")
}
func (UnimplementedMQTTReceiverServer) mustEmbedUnimplementedMQTTReceiverServer() {}
func (UnimplementedMQTTReceiverServer) testEmbeddedByValue()                      {}

// UnsafeMQTTReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MQTTReceiverServer will
// result in compilation errors.
type UnsafeMQTTReceiverServer interface {
	mustEmbedUnimplementedMQTTReceiverServer()
}

func RegisterMQTTReceiverServer(s grpc.ServiceRegistrar, srv MQTTReceiverServer) {
	// If the following call pancis, it indicates UnimplementedMQTTReceiverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MQTTReceiver_ServiceDesc, srv)
}

func _MQTTReceiver_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTTReceiver_SubscribeParameters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MQTTReceiverServer).SubscribeParameters(m, &grpc.GenericServerStream[SubscribeRequest, ParameterUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MQTTReceiver_SubscribeParametersServer = grpc.ServerStreamingServer[ParameterUpdate]

func _MQTTReceiver_ListSystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).ListSystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_ListSystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).ListSystems(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTTReceiver_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTTReceiver_ListParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).ListParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_ListParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).ListParameters(ctx, req.(*ListParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTTReceiver_GetParameterHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).GetParameterHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_GetParameterHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).GetParameterHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTTReceiver_SetParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTReceiverServer).SetParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQTTReceiver_SetParameter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTReceiverServer).SetParameter(ctx, req.(*SetParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MQTTReceiver_ServiceDesc is the grpc.ServiceDesc for MQTTReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MQTTReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brutus.MQTTReceiver",
	HandlerType: (*MQTTReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MQTTReceiver_Login_Handler,
		},
		{
			MethodName: "ListSystems",
			Handler:    _MQTTReceiver_ListSystems_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _MQTTReceiver_ListDevices_Handler,
		},
		{
			MethodName: "ListParameters",
			Handler:    _MQTTReceiver_ListParameters_Handler,
		},
		{
			MethodName: "GetParameterHistory",
			Handler:    _MQTTReceiver_GetParameterHistory_Handler,
		},
		{
			MethodName: "SetParameter",
			Handler:    _MQTTReceiver_SetParameter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeParameters",
			Handler:       _MQTTReceiver_SubscribeParameters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/brutus.proto",
}
