// proto/brutus.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/brutus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Parameter     string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_brutus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Value) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Value) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Parameter     string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_brutus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Command) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Запрос истории параметров
type HistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Parameter      string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"` // начало периода (в миллисекундах)
	EndTimestamp   int64                  `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`       // конец периода (в миллисекундах)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_brutus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HistoryRequest) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *HistoryRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *HistoryRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

// Ответ с историей значений
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // список значений с временными метками
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_brutus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brutus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_brutus_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_brutus_proto protoreflect.FileDescriptor

const file_proto_brutus_proto_rawDesc = "" +
	"\n" +
	"\x12proto/brutus.proto\x12\x06brutus\"q\n" +
	"\x05Value\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"U\n" +
	"\aCommand\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x94\x01\n" +
	"\x0eHistoryRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x03R\fendTimestamp\"8\n" +
	"\x0fHistoryResponse\x12%\n" +
	"\x06values\x18\x01 \x03(\v2\r.brutus.ValueR\x06values2\x85\x01\n" +
	"\fMQTTReceiver\x124\n" +
	"\fDataExchange\x12\x0f.brutus.Command\x1a\r.brutus.Value\"\x00(\x010\x01\x12?\n" +
	"\n" +
	"GetHistory\x12\x16.brutus.HistoryRequest\x1a\x17.brutus.HistoryResponse\"\x00B\x0eZ\fbrutus/protob\x06proto3"

var (
	file_proto_brutus_proto_rawDescOnce sync.Once
	file_proto_brutus_proto_rawDescData []byte
)

func file_proto_brutus_proto_rawDescGZIP() []byte {
	file_proto_brutus_proto_rawDescOnce.Do(func() {
		file_proto_brutus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_brutus_proto_rawDesc), len(file_proto_brutus_proto_rawDesc)))
	})
	return file_proto_brutus_proto_rawDescData
}

var file_proto_brutus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_brutus_proto_goTypes = []any{
	(*Value)(nil),           // 0: brutus.Value
	(*Command)(nil),         // 1: brutus.Command
	(*HistoryRequest)(nil),  // 2: brutus.HistoryRequest
	(*HistoryResponse)(nil), // 3: brutus.HistoryResponse
}
var file_proto_brutus_proto_depIdxs = []int32{
	0, // 0: brutus.HistoryResponse.values:type_name -> brutus.Value
	1, // 1: brutus.MQTTReceiver.DataExchange:input_type -> brutus.Command
	2, // 2: brutus.MQTTReceiver.GetHistory:input_type -> brutus.HistoryRequest
	0, // 3: brutus.MQTTReceiver.DataExchange:output_type -> brutus.Value
	3, // 4: brutus.MQTTReceiver.GetHistory:output_type -> brutus.HistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_brutus_proto_init() }
func file_proto_brutus_proto_init() {
	if File_proto_brutus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_brutus_proto_rawDesc), len(file_proto_brutus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brutus_proto_goTypes,
		DependencyIndexes: file_proto_brutus_proto_depIdxs,
		MessageInfos:      file_proto_brutus_proto_msgTypes,
	}.Build()
	File_proto_brutus_proto = out.File
	file_proto_brutus_proto_goTypes = nil
	file_proto_brutus_proto_depIdxs = nil
}
